#   by-EAjks.Com Go Development Environments
#   Copyright (C) 2025-2025 Andrea and Eric DELAGE <Contact@by-EAjks.Com>
#
#   This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program.  If not, see <https://www.gnu.org/licenses/>.

name: (CI/CD) Build and deploy the go-devenv-* container images
on:
  push:
    branches:
      - 'main'
      - 'feature/cpp-only/**'
      - 'issue/cpp-only/**'
      - 'release/cpp-only/**'
    tags:
      - '\d+.\d+.\d+'
    paths:
      - '.github/workflows/build-and-push.yaml'
      - 'Definitions/**'
env:
  IMAGE_REPOSITORY: eajkseajks
jobs:
  build-and-push-container-images:
    name: Build and push the container images
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: go-devenv
    steps:
      - name: Checkout the git repository
        uses: actions/checkout@v6.0.1
        # https://github.com/actions/checkout/tags
      - name: Install cosign
        uses: sigstore/cosign-installer@v4.0.0
        with:
          cosign-release: v3.0.2
        # https://github.com/sigstore/cosign-installer/tags
        # https://github.com/sigstore/cosign/releases
      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v3.11.1
        # https://github.com/docker/setup-buildx-action/tags
      - name: Login to ${{env.IMAGE_REPOSITORY}} registry
        uses: docker/login-action@v3.6.0
        with:
          registry: docker.io
          username: ${{secrets.DOCKER_HUB_USERNAME}}
          password: ${{secrets.DOCKER_HUB_ACCESS_TOKEN}}
        # https://github.com/docker/login-action/tags
      - id: extract-metadata-core
        name: Extract the ${{env.IMAGE_NAME}}-core metadata
        uses: docker/metadata-action@v5.10.0
        with:
          context: workflow
          images: |
            ${{env.IMAGE_REPOSITORY}}/${{env.IMAGE_NAME}}-core
          flavor: |
            latest=false
            prefix=,onlatest=true
            suffix=,onlatest=true
          tags: |
            type=match,pattern=\d+.\d+.\d+
            type=match,pattern=\d+.\d+
            type=match,pattern=\d+
            type=ref,event=branch
            type=ref,prefix=pr-,event=pr
        # https://github.com/docker/metadata-action/tags
      - id: build-and-push-core
        name: Build the ${{env.IMAGE_NAME}}-core image and push it to the ${{env.IMAGE_REPOSITORY}} registry
        uses: docker/build-push-action@v6.18.0
        with:
          context: .
          file: ./Definitions/Core/Dockerfile
          tags: ${{steps.extract-metadata-core.outputs.tags}}
          labels: ${{steps.extract-metadata-core.outputs.labels}}
          push: true
        # https://github.com/docker/build-push-action/tags
      - name: Sign the ${{env.IMAGE_NAME}}-core image with GitHub OIDC token
        env:
          TAGS: ${{steps.extract-metadata-core.outputs.tags}}
          DIGEST: ${{steps.build-and-push-core.outputs.digest}}
        run: |
          for TAG in ${TAGS}; do
            cosign sign --yes ${TAG}@${DIGEST}
          done
